%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\rsk02\Documents\GitHub\TechForParalysis\Code\Model\ThoracoscapularShoulderPaperMaterials\Scripts\BatchScaling\IK output_1\ABD_NL001_FP03_ik.mot
%
% Auto-generated by MATLAB on 18-Mar-2020 08:43:16
fileID='ABD_NL001_FP03_ik.mot';
filePath='';

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 18); % using delimitedTextImportOptions function,
% then uses NumVariables to collect the variable names for all 18 of them.

% Specify range and delimiter
opts.DataLines = [12, Inf]; % Actual numeric data starts from 12
opts.Delimiter = "\t"; % uses delimeter tab for separation

% Specify column names and types
opts.VariableNames = ["time", "ground_thorax_rot_x", "ground_thorax_rot_y", "ground_thorax_rot_z", "ground_thorax_tx", "ground_thorax_ty", "ground_thorax_tz", "clav_prot", "clav_elev", "scapula_abduction", "scapula_elevation", "scapula_upward_rot", "scapula_winging", "plane_elv", "shoulder_elv", "axial_rot", "elbow_flexion", "pro_sup"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ABDNL001FP03ik = readtable("C:\Users\rsk02\Documents\GitHub\TechForParalysis\Code\Model\ThoracoscapularShoulderPaperMaterials\Scripts\BatchScaling\IK output_1\ABD_NL001_FP03_ik.mot", opts);


%% Clear temporary variables
clear opts